export interface Plant {
  id: string
  name: string
  scientificName: string
  price: number
  category: string
  difficulty: "Easy" | "Medium" | "Hard"
  lightRequirement: "Low" | "Medium" | "High"
  wateringFrequency: string
  description: string
  image: string
  inStock: boolean
  featured: boolean
}

export const plantsData: Plant[] = [
  {
    id: "1",
    name: "Monstera Deliciosa",
    scientificName: "Monstera deliciosa",
    price: 2499,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "A stunning tropical plant with large, split leaves that adds dramatic flair to any space.",
    image: "/monstera-deliciosa-plant-in-white-pot.png",
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    name: "Snake Plant",
    scientificName: "Sansevieria trifasciata",
    price: 1299,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Low",
    wateringFrequency: "Bi-weekly",
    description: "Perfect for beginners, this hardy plant thrives in low light and requires minimal care.",
    image: "/snake-plant-sansevieria-in-modern-pot.png",
    inStock: true,
    featured: true,
  },
  {
    id: "3",
    name: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    price: 3999,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "High",
    wateringFrequency: "Weekly",
    description: "An elegant statement plant with large, violin-shaped leaves that brightens any room.",
    image: "/fiddle-leaf-fig-tree-in-ceramic-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "4",
    name: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    price: 899,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Low",
    wateringFrequency: "Weekly",
    description: "Beautiful white blooms and glossy green leaves make this a popular choice for homes.",
    image: "/peace-lily-with-white-flowers-in-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "5",
    name: "Rubber Plant",
    scientificName: "Ficus elastica",
    price: 1899,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Glossy, dark green leaves and easy care make this a perfect indoor companion.",
    image: "/rubber-plant-terracotta.png",
    inStock: true,
    featured: true,
  },
  {
    id: "6",
    name: "Pothos",
    scientificName: "Epipremnum aureum",
    price: 699,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Low",
    wateringFrequency: "Weekly",
    description: "A trailing vine perfect for hanging baskets or shelves, very forgiving for beginners.",
    image: "/golden-pothos-hanging-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "7",
    name: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    price: 1599,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Low",
    wateringFrequency: "Monthly",
    description: "Extremely low maintenance with glossy, waxy leaves that tolerate neglect beautifully.",
    image: "/zz-plant-zamioculcas-in-modern-white-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "8",
    name: "Bird of Paradise",
    scientificName: "Strelitzia reginae",
    price: 4999,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "High",
    wateringFrequency: "Weekly",
    description: "Dramatic tropical plant with large paddle-shaped leaves and stunning orange flowers.",
    image: "/bird-of-paradise-plant-with-large-leaves.png",
    inStock: true,
    featured: true,
  },
  {
    id: "9",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis",
    price: 799,
    category: "Succulent",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Bi-weekly",
    description: "Medicinal succulent with healing properties, perfect for sunny windowsills.",
    image: "/aloe-vera-terracotta.png",
    inStock: true,
    featured: false,
  },
  {
    id: "10",
    name: "Jade Plant",
    scientificName: "Crassula ovata",
    price: 999,
    category: "Succulent",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Bi-weekly",
    description: "Lucky money tree with thick, glossy leaves that brings prosperity and good fortune.",
    image: "/jade-plant-crassula-ovata-in-ceramic-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "11",
    name: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    price: 1199,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "Medium",
    wateringFrequency: "Twice weekly",
    description: "Lush, feathery fronds that add a tropical feel to any room.",
    image: "/boston-fern-in-hanging-basket.png",
    inStock: true,
    featured: false,
  },
  {
    id: "12",
    name: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    price: 599,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Easy-care plant with arching leaves and baby plantlets.",
    image: "/spider-plant-with-babies-in-white-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "13",
    name: "Philodendron",
    scientificName: "Philodendron hederaceum",
    price: 899,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Low",
    wateringFrequency: "Weekly",
    description: "Heart-shaped leaves on trailing vines, perfect for hanging baskets.",
    image: "/heart-leaf-philodendron-trailing-plant.png",
    inStock: true,
    featured: false,
  },
  {
    id: "14",
    name: "Dracaena",
    scientificName: "Dracaena marginata",
    price: 1799,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Tall, architectural plant with spiky leaves and red edges.",
    image: "/dracaena-marginata-dragon-tree-in-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "15",
    name: "English Ivy",
    scientificName: "Hedera helix",
    price: 699,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Low",
    wateringFrequency: "Weekly",
    description: "Classic trailing plant with distinctive lobed leaves.",
    image: "/english-ivy-trailing-in-decorative-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "16",
    name: "Echeveria",
    scientificName: "Echeveria elegans",
    price: 499,
    category: "Succulent",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Bi-weekly",
    description: "Beautiful rosette-shaped succulent with blue-green leaves.",
    image: "/echeveria-succulent-rosette-in-small-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "17",
    name: "Haworthia",
    scientificName: "Haworthia fasciata",
    price: 599,
    category: "Succulent",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Bi-weekly",
    description: "Small succulent with distinctive white stripes on dark green leaves.",
    image: "/haworthia-zebra-plant-succulent.png",
    inStock: true,
    featured: false,
  },
  {
    id: "18",
    name: "String of Pearls",
    scientificName: "Senecio rowleyanus",
    price: 799,
    category: "Succulent",
    difficulty: "Medium",
    lightRequirement: "High",
    wateringFrequency: "Bi-weekly",
    description: "Unique trailing succulent with bead-like leaves.",
    image: "/string-of-pearls-succulent-hanging-plant.png",
    inStock: true,
    featured: false,
  },
  {
    id: "19",
    name: "Cactus Mix",
    scientificName: "Various species",
    price: 899,
    category: "Succulent",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Monthly",
    description: "Collection of small desert cacti in decorative arrangement.",
    image: "/small-cactus-collection-in-terracotta-pots.png",
    inStock: true,
    featured: false,
  },
  {
    id: "20",
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    price: 1299,
    category: "Flowering",
    difficulty: "Medium",
    lightRequirement: "High",
    wateringFrequency: "Weekly",
    description: "Fragrant purple flowers and silvery foliage, perfect for aromatherapy.",
    image: "/lavender-plant-with-purple-flowers-in-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "21",
    name: "Geranium",
    scientificName: "Pelargonium zonale",
    price: 899,
    category: "Flowering",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Weekly",
    description: "Bright, colorful flowers that bloom continuously in good conditions.",
    image: "/red-geranium-flowers-in-clay-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "22",
    name: "Marigold",
    scientificName: "Tagetes patula",
    price: 399,
    category: "Flowering",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Daily",
    description: "Vibrant orange and yellow flowers that repel garden pests.",
    image: "/orange-marigold-flowers-in-garden-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "23",
    name: "Petunias",
    scientificName: "Petunia hybrida",
    price: 699,
    category: "Flowering",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Daily",
    description: "Trumpet-shaped flowers in various colors, perfect for containers.",
    image: "/colorful-petunia-flowers-in-hanging-basket.png",
    inStock: true,
    featured: false,
  },
  {
    id: "24",
    name: "Impatiens",
    scientificName: "Impatiens walleriana",
    price: 599,
    category: "Flowering",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Daily",
    description: "Shade-loving flowers that bloom continuously in various colors.",
    image: "/pink-impatiens-flowers-in-decorative-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "25",
    name: "Begonia",
    scientificName: "Begonia semperflorens",
    price: 799,
    category: "Flowering",
    difficulty: "Medium",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Waxy flowers and glossy leaves, excellent for shaded areas.",
    image: "/red-begonia-flowers-with-glossy-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "26",
    name: "Tomato Plant",
    scientificName: "Solanum lycopersicum",
    price: 299,
    category: "Outdoor",
    difficulty: "Medium",
    lightRequirement: "High",
    wateringFrequency: "Daily",
    description: "Fresh homegrown tomatoes from your own garden.",
    image: "/tomato-plant-with-red-tomatoes-in-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "27",
    name: "Basil",
    scientificName: "Ocimum basilicum",
    price: 199,
    category: "Outdoor",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Daily",
    description: "Aromatic herb perfect for cooking and natural pest control.",
    image: "/basil-herb-plant-with-green-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "28",
    name: "Mint",
    scientificName: "Mentha spicata",
    price: 199,
    category: "Outdoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Daily",
    description: "Refreshing herb that spreads quickly and smells amazing.",
    image: "/mint-herb-plant-in-decorative-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "29",
    name: "Rosemary",
    scientificName: "Rosmarinus officinalis",
    price: 399,
    category: "Outdoor",
    difficulty: "Medium",
    lightRequirement: "High",
    wateringFrequency: "Weekly",
    description: "Woody herb with needle-like leaves and strong aroma.",
    image: "/rosemary-herb-plant-with-needle-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "30",
    name: "Sunflower",
    scientificName: "Helianthus annuus",
    price: 299,
    category: "Outdoor",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Daily",
    description: "Tall, cheerful flowers that follow the sun throughout the day.",
    image: "/sunflower-plant-with-yellow-bloom.png",
    inStock: true,
    featured: false,
  },
  {
    id: "31",
    name: "Calathea",
    scientificName: "Calathea ornata",
    price: 1599,
    category: "Indoor",
    difficulty: "Hard",
    lightRequirement: "Low",
    wateringFrequency: "Weekly",
    description: "Prayer plant with stunning patterned leaves that fold at night.",
    image: "/calathea-plant-with-patterned-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "32",
    name: "Anthurium",
    scientificName: "Anthurium andraeanum",
    price: 2199,
    category: "Flowering",
    difficulty: "Medium",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Glossy heart-shaped flowers in bright red with dark green leaves.",
    image: "/anthurium-plant-with-red-heart-flowers.png",
    inStock: true,
    featured: false,
  },
  {
    id: "33",
    name: "Orchid",
    scientificName: "Phalaenopsis amabilis",
    price: 2999,
    category: "Flowering",
    difficulty: "Hard",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Elegant white flowers that can bloom for months with proper care.",
    image: "/orchid-plant-with-purple-flowers.png",
    inStock: true,
    featured: false,
  },
  {
    id: "34",
    name: "Croton",
    scientificName: "Codiaeum variegatum",
    price: 1399,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "High",
    wateringFrequency: "Weekly",
    description: "Colorful foliage plant with leaves in yellow, red, and green.",
    image: "/croton-plant-with-colorful-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "35",
    name: "Norfolk Pine",
    scientificName: "Araucaria heterophylla",
    price: 2799,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "High",
    wateringFrequency: "Weekly",
    description: "Living Christmas tree that can be decorated year-round.",
    image: "/norfolk-pine-small-tree-in-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "36",
    name: "Yucca",
    scientificName: "Yucca elephantipes",
    price: 2299,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Bi-weekly",
    description: "Architectural plant with sword-like leaves and thick trunk.",
    image: "/yucca-plant-with-sword-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "37",
    name: "Parlor Palm",
    scientificName: "Chamaedorea elegans",
    price: 1799,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Low",
    wateringFrequency: "Weekly",
    description: "Elegant palm that thrives in low light conditions.",
    image: "/parlor-palm-with-feathery-fronds.png",
    inStock: true,
    featured: false,
  },
  {
    id: "38",
    name: "Areca Palm",
    scientificName: "Dypsis lutescens",
    price: 3499,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Feathery palm fronds that create a tropical atmosphere.",
    image: "/areca-palm-with-golden-stems.png",
    inStock: true,
    featured: false,
  },
  {
    id: "39",
    name: "Ponytail Palm",
    scientificName: "Beaucarnea recurvata",
    price: 2599,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Monthly",
    description: "Unique plant with bulbous base and long, curly leaves.",
    image: "/ponytail-palm-with-curly-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "40",
    name: "Dieffenbachia",
    scientificName: "Dieffenbachia seguine",
    price: 1299,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Large variegated leaves with cream and green patterns.",
    image: "/dieffenbachia-with-spotted-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "41",
    name: "Aglaonema",
    scientificName: "Aglaonema commutatum",
    price: 1199,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Low",
    wateringFrequency: "Weekly",
    description: "Chinese evergreen with beautiful silver and green foliage.",
    image: "/aglaonema-with-silver-green-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "42",
    name: "Schefflera",
    scientificName: "Schefflera actinophylla",
    price: 1899,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Umbrella tree with glossy compound leaves.",
    image: "/schefflera-umbrella-plant-in-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "43",
    name: "Fittonia",
    scientificName: "Fittonia albivenis",
    price: 699,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "Low",
    wateringFrequency: "Twice weekly",
    description: "Nerve plant with intricate white or pink vein patterns.",
    image: "/fittonia-nerve-plant-with-veined-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "44",
    name: "Peperomia",
    scientificName: "Peperomia obtusifolia",
    price: 799,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Compact plant with thick, waxy leaves in various patterns.",
    image: "/peperomia-plant-with-thick-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "45",
    name: "Maranta",
    scientificName: "Maranta leuconeura",
    price: 1399,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "Low",
    wateringFrequency: "Weekly",
    description: "Prayer plant with beautiful red veined leaves that fold at night.",
    image: "/maranta-prayer-plant-with-oval-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "46",
    name: "Hoya",
    scientificName: "Hoya carnosa",
    price: 1599,
    category: "Indoor",
    difficulty: "Medium",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Wax plant with thick succulent-like leaves and fragrant flowers.",
    image: "/hoya-wax-plant-with-waxy-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "47",
    name: "Tradescantia",
    scientificName: "Tradescantia zebrina",
    price: 599,
    category: "Indoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Weekly",
    description: "Wandering jew with purple and silver striped leaves.",
    image: "/tradescantia-wandering-jew-trailing.png",
    inStock: true,
    featured: false,
  },
  {
    id: "48",
    name: "Coleus",
    scientificName: "Plectranthus scutellarioides",
    price: 499,
    category: "Outdoor",
    difficulty: "Easy",
    lightRequirement: "Medium",
    wateringFrequency: "Daily",
    description: "Colorful foliage plant with leaves in purple, red, and green.",
    image: "/coleus-plant-with-colorful-foliage.png",
    inStock: true,
    featured: false,
  },
  {
    id: "49",
    name: "Caladium",
    scientificName: "Caladium bicolor",
    price: 899,
    category: "Outdoor",
    difficulty: "Medium",
    lightRequirement: "Medium",
    wateringFrequency: "Daily",
    description: "Heart-shaped leaves with stunning pink and green patterns.",
    image: "/caladium-with-heart-shaped-leaves.png",
    inStock: true,
    featured: false,
  },
  {
    id: "50",
    name: "Zinnia",
    scientificName: "Zinnia elegans",
    price: 299,
    category: "Flowering",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Daily",
    description: "Bright, cheerful flowers that attract butterflies to your garden.",
    image: "/zinnia-flowers-bright-colors-in-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "51",
    name: "Cosmos",
    scientificName: "Cosmos bipinnatus",
    price: 399,
    category: "Flowering",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Weekly",
    description: "Delicate flowers with feathery foliage that sway in the breeze.",
    image: "/cosmos-flowers-pink-white-in-pot.png",
    inStock: true,
    featured: false,
  },
  {
    id: "52",
    name: "Nasturtium",
    scientificName: "Tropaeolum majus",
    price: 299,
    category: "Flowering",
    difficulty: "Easy",
    lightRequirement: "High",
    wateringFrequency: "Daily",
    description: "Edible flowers in bright orange and yellow with peppery taste.",
    image: "/nasturtium-flowers-orange-yellow.png",
    inStock: true,
    featured: false,
  },
]

export const categories = ["All", "Indoor", "Outdoor", "Succulent", "Flowering"]
export const difficulties = ["All", "Easy", "Medium", "Hard"]
export const lightRequirements = ["All", "Low", "Medium", "High"]

export function filterPlants(
  plants: Plant[],
  searchQuery: string,
  category: string,
  difficulty: string,
  lightRequirement: string,
): Plant[] {
  return plants.filter((plant) => {
    const matchesSearch =
      plant.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      plant.scientificName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      plant.description.toLowerCase().includes(searchQuery.toLowerCase())

    const matchesCategory = category === "All" || plant.category === category
    const matchesDifficulty = difficulty === "All" || plant.difficulty === difficulty
    const matchesLight = lightRequirement === "All" || plant.lightRequirement === lightRequirement

    return matchesSearch && matchesCategory && matchesDifficulty && matchesLight
  })
}
